name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Install dependencies
        working-directory: ./src/main/resources/static/js
        run: npm install
      - name: Run tests
        working-directory: ./src/main/resources/static/js
        run: npm test
